---
- name: Join Worker Nodes
  hosts: workers
  become: true
  vars:
    node_conn_string: "{{ lookup('file', 'join_command.sh') }}"

  tasks:
    - name: 1. Add Worker Nodes To The Controller
      ansible.builtin.command: '{{ node_conn_string }}'
      changed_when: false
      throttle: 1
